### ISSUE TITLE
not working with flutter web.

### ISSUE THREAD

**Issue by abhaySquare** [MohamedAbd0/widgets_to_image#12]
it give me error as matrix4[0] == EngineFlutterDisplay.instance.devicePixelRatio &&
            matrix4[5] == EngineFlutterDisplay.instance.devicePixelRatio
is not true

**Comment by MohamedAbd0** [comment]
How can upgrade to  V1.0.0 

<img width="1312" alt="web" src="https://github.com/MohamedAbd0/widgets_to_image/assets/32939129/678e6a22-84ac-450a-b7dc-80dd8cae043d">

**Comment by BottlePumpkin** [comment]
not working  at --web-renderer html mode
