### ISSUE TITLE
Does not capture web view

### ISSUE THREAD

**Issue by dev-kasibhatla** [MohamedAbd0/widgets_to_image#6]
This plugin does not capture web view when it is in the widget tree. 

Relevant implementation details:
Webview: flutter_inappwebview: ^6.0.0-beta.22
Platform: iOS
```
InAppWebViewSettings(
    useHybridComposition: true,
    javaScriptEnabled: true,
    transparentBackground: true,
  );
```
Plugin version: widgets_to_image: ^0.0.2
Flutter 3.7.8

**Comment by MohamedAbd0** [comment]
I upload the new version to solve this pugs.
