### ISSUE TITLE
not  working on mobile 

### ISSUE THREAD

**Issue by MTEV** [MohamedAbd0/widgets_to_image#7]
after test on mobile not working  working only on emulator 
   final bytes =
                                              await controller.capture();
                                          setState(() {
                                            this.bytes = bytes;
                                          });
                                      //  MemoryImage(bytes!);  //  if  commit or not not  working 
                                          //Image.memory(this.bytes!); ///  if  commit or not not  working 
                                          final image =
                                              pw.MemoryImage(this.bytes!);

**Comment by MohamedAbd0** [comment]
I upload the new version to solve this pugs.
