### ISSUE TITLE
flutter 3.10.6 error

### ISSUE THREAD

**Issue by liumingsongning** [MohamedAbd0/widgets_to_image#9]
`RenderView renderView = RenderView(
			child: RenderPositionedBox(alignment: alignment, child: repaintBoundary),
			configuration: ViewConfiguration(
				size: size,
				devicePixelRatio: devicePixelRatio,
			),
			window: WidgetsBinding.instance!.platformDispatcher.views.first,
		);`
` Error: No named parameter with the name 'window'.
widget_to_image.dart:32
			window: WidgetsBinding.instance!.platformDispatcher.views.first,
			^^^^^^`

**Comment by liumingsongning** [comment]
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 12.6.2 21G317 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[!] Network resources             
    ✗ An HTTP error occurred while checking "https://github.com/": Operation timed out

! Doctor found issues in 1 category.`

**Comment by MohamedAbd0** [comment]
I upload the new version to solve this pugs.
